# -*- coding: utf-8 -*-
"""TASK 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bUuprClf-XdgBwmfEGyaGKCs_yGnp-o

1.Write a program that uses input to prompt a user for their name and then welcomes them.
"""

a = input("Enter your name:")
print("Hello",a)
print("Welcome to my repo!")

"""2.Write a program which prompts the user for a Celsius temperature, convert the temperature to Fahrenheit, and print out the converted temperature."""

celsius = float(input("Enter temperature in Celsius:"))
faren = (celsius * 1.8)+32
print(celsius," ℃ is",faren,"℉")

"""3.Write a Python program to convert degree to radian."""

pi=3.14
degree = float(input("Enter the degree:"))
rad = degree*pi/180
print(degree,"degree is equal to","%.4f" %rad ,"Rad.")